### ISSUE TITLE
x_train , y_train의 shape차이는 왜 일까요?

### ISSUE THREAD

**Issue by ggokka** [kairess/stock_crypto_price_prediction#1]
x_train과 y_train의 shape를 확인해보면

x_train (1057, 50, 1)
y_train (1057,)

이렇게 나오고 있는데요. 
차이가 나는 이유는 x_train만 reshape를 했기 때문이더라구요.
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

그 이유가 궁금합니다

**Comment by kairess** [comment]
@ggokka 죄송해요, 답변이 늦었습니다. 왜냐하면
x_train은 예측하기위한 인풋값이고 (50일치 데이터)
y_train은 50일치 데이터를 통해 나온 51일차(1일치)의 예측값이기 때문입니다.

결국 이 모델은 최근 50일간의 데이터를 보고 다음날 1일의 데이터를 예측하니까요.

**Comment by ggokka** [comment]
각각의 50일치 데이타라면, x_train의 차원이  (1057,50) 이어도 무방하지 않을까요? 왜 굳이  (1057, 50, 1) 일까요? 2차원 데이타와 3차원 데이타는 엄연히 다르잖아요. 꼭 그렇게 해야하는 이유가 있나요?

**Comment by kairess** [comment]
@ggokka 저도 다른 예제를 참고한거라 (1057, 50) 으로 테스트해보진 않았어요. 근데 LSTM 레이어가 인풋으로 받을때 그렇게 정의되어 있는것 같아요

**Comment by kosungyeol** [comment]
혹시 다음날 값을 산출 할 수는 없나요?

**Comment by kairess** [comment]
@kosungyeol 영상 보시면 pred 값을 프린트하시면 다음날 값들이 나오게끔 되어있어요
